apiVersion: v1
kind: ConfigMap
metadata:
  name: librespeed-env
  namespace: final
  labels:
    app.kubernetes.io/name: librespeed
    app.kubernetes.io/instance: librespeed
data:
  MODE: "frontend"
  DB_TYPE: "mysql"
  TELEMETRY: "true"
  ENABLE_ID_OBFUSCATION: "true"
  REDACT_IP_ADDRESSES: "true"
