apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
spec:
  accessModes:
    - ReadWriteOnce 
  volumeMode: Filesystem 
  resources:
    requests:
      storage: 30Gi 
  storageClassName: local-path
